name: deploy-gh-pages-manually

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'
    - name: Setup node & sass
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: install sass
      run: npm install -g sass
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      working-directory: ./src
      run: dotnet fornax build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./src/_public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
